Deprecate the high level interface
pypa/pep517 pull request #108
Opened 2021-02-01 06:56 UTC by hexagonrecursion

#91

> Add a deprecation warning when pep517.build is used
> Add a deprecation warning when pep517.checkis used

2021-02-01 10:21 UTC, pradyunsg requested changes
Thanks for the PR!

I don't think these should be print statements, but rather log.warning(...) calls inside the main function. That'll allow downstream users to use all of logging's capabilities to handle and manage these logs.

2021-02-01 10:22 UTC, pradyunsg commented on pep517/check.py
> +    print(ansi('pep517.check is deprecated. Consider switching to https://pypi.org/project/build/', 'red'))
And, assuming we do change that, this should also not be wrapped in ansi red IMO

2021-02-01 12:28 UTC, hexagonrecursion commented
> Thanks for the PR!
> 
> I don't think these should be print statements, but rather log.warning(...) calls inside the main function. That'll allow downstream users to use all of logging's capabilities to handle and manage these logs.

Should I put log.warning in main() or at the top of the module after the imports?

2021-02-01 12:44 UTC, hexagonrecursion commented
Done

2021-02-02 08:32 UTC, pradyunsg reviewed
Almost there!

2021-02-02 08:32 UTC, pradyunsg commented on pep517/build.py
> +    log.warning('pep517.build is deprecated. Consider switching to https://pypi.org/project/build/', stacklevel=2)
I don't think stacklevel is necessary here.

2021-02-02 09:41 UTC, hexagonrecursion commented
done

2021-02-02 09:54 UTC, pradyunsg approved these changes

2021-02-02 09:54 UTC, merged